<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>DTO</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="alaasmagi.Base.Contracts.DTO" Version="1.0.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\Helpers\Helpers.csproj" />
    </ItemGroup>

</Project>
