<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="alaasmagi.Base.DataAccess.EF" Version="1.0.3" />
      <PackageReference Include="alaasmagi.Base.Domain" Version="1.0.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DataAccess\Entities\" />
      <Folder Include="DataAccess\Repositories\" />
    </ItemGroup>

</Project>
