<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="alaasmagi.Base.Application" Version="1.0.3" />
      <PackageReference Include="alaasmagi.Base.DTO" Version="1.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\App.Contract\App.Contract.csproj" />
      <ProjectReference Include="..\App.Domain\App.Domain.csproj" />
    </ItemGroup>

</Project>
